"""
Catalog Models - Data models for artifact metadata.

Defines the Artifact and UpdateResult data models used by the
artifact catalog database and update checker.

Author
------
Claude Code (Anthropic)

Contributor
-----------
Steven Siebert

License
-------
MIT License
Copyright (c) 2024 geoint.org
See LICENSE file for full text.

Created
-------
2026-02-06

Modified
--------
2026-02-06
"""

# Standard library
from typing import Any


class Artifact:
    """Metadata for a GRDL processor or GRDK workflow artifact.

    Parameters
    ----------
    name : str
        Artifact name.
    version : str
        Semantic version string.
    artifact_type : str
        One of 'grdl_processor' or 'grdk_workflow'.
    description : str
        Human-readable description.
    author : str
        Author name.
    license : str
        License identifier.
    pypi_package : Optional[str]
        PyPI package name.
    conda_package : Optional[str]
        Conda package name.
    conda_channel : Optional[str]
        Conda channel (e.g., 'conda-forge').
    processor_class : Optional[str]
        Fully-qualified Python class path (grdl_processor only).
    processor_version : Optional[str]
        @processor_version value (grdl_processor only).
    processor_type : Optional[str]
        One of 'transform', 'detector', 'decomposition' (grdl_processor only).
    yaml_definition : Optional[str]
        Full YAML workflow definition (grdk_workflow only).
    python_dsl : Optional[str]
        Full Python DSL source (grdk_workflow only).
    tags : Optional[Dict[str, List[str]]]
        Tag key-value pairs (grdk_workflow only).
    id : Optional[int]
        Database row ID (set after insertion).
    requires_global_pass : bool
        Whether this processor requires a global pass over the full
        image before per-chip/per-tile processing (grdl_processor only).
    alternatives : Optional[List[Dict[str, Any]]]
        Alternative processor implementations, each a dict with keys
        ``processor_name`` (str), ``priority`` (int, lower = higher),
        and ``compatibility_notes`` (str).  Used by the execution
        resolver for graceful degradation (e.g., CPU fallback).
    param_schema : Optional[Dict[str, Any]]
        JSON Schema (draft 2020-12) describing the processor's tunable
        parameters.  Generated by ``extract_param_schema`` at cataloging
        time so that tools like grdk can build UI controls without
        importing the processor code (grdl_processor only).
    """

    def __init__(
        self,
        name: str,
        version: str,
        artifact_type: str,
        description: str = "",
        author: str = "",
        license: str = "MIT",
        pypi_package: str | None = None,
        conda_package: str | None = None,
        conda_channel: str | None = None,
        processor_class: str | None = None,
        processor_version: str | None = None,
        processor_type: str | None = None,
        yaml_definition: str | None = None,
        python_dsl: str | None = None,
        tags: dict[str, list[str]] | None = None,
        id: int | None = None,
        requires_global_pass: bool = False,
        alternatives: list[dict[str, Any]] | None = None,
        param_schema: dict[str, Any] | None = None,
    ) -> None:
        if artifact_type not in ("grdl_processor", "grdk_workflow"):
            raise ValueError(
                f"artifact_type must be 'grdl_processor' or 'grdk_workflow', "
                f"got {artifact_type!r}"
            )
        self.id = id
        self.name = name
        self.version = version
        self.artifact_type = artifact_type
        self.description = description
        self.author = author
        self.license = license
        self.pypi_package = pypi_package
        self.conda_package = conda_package
        self.conda_channel = conda_channel
        self.processor_class = processor_class
        self.processor_version = processor_version
        self.processor_type = processor_type
        self.yaml_definition = yaml_definition
        self.python_dsl = python_dsl
        self.tags = tags or {}
        self.requires_global_pass = requires_global_pass
        self.alternatives: list[dict[str, Any]] = alternatives or []
        self.param_schema: dict[str, Any] | None = param_schema

    def __repr__(self) -> str:
        return (
            f"Artifact(name={self.name!r}, version={self.version!r}, "
            f"type={self.artifact_type!r})"
        )


class UpdateResult:
    """Result of checking a single artifact for updates.

    Parameters
    ----------
    artifact : Artifact
        The artifact that was checked.
    source : str
        Update source ('pypi' or 'conda').
    current_version : str
        Currently installed version.
    latest_version : Optional[str]
        Latest available version, or None if check failed.
    update_available : bool
        Whether a newer version is available.
    error : Optional[str]
        Error message if the check failed.
    """

    def __init__(
        self,
        artifact: Artifact,
        source: str,
        current_version: str,
        latest_version: str | None = None,
        update_available: bool = False,
        error: str | None = None,
    ) -> None:
        self.artifact = artifact
        self.source = source
        self.current_version = current_version
        self.latest_version = latest_version
        self.update_available = update_available
        self.error = error

    def __repr__(self) -> str:
        if self.update_available:
            return (
                f"UpdateResult({self.artifact.name!r}: "
                f"{self.current_version} → {self.latest_version})"
            )
        return f"UpdateResult({self.artifact.name!r}: up to date)"
